export enum ActionTypeStates {
  INPROGRESS = "_INPROGRESS",
  SUCCESS = "_SUCCESS",
  FAIL = "_FAIL",
  UNAUTHORISED = '_UNAUTHORISED'
}

enum ActionTypeKeys {
  SIGNIN_INPROGRESS = "SIGNIN_INPROGRESS",
  SIGNIN_SUCCESS = "SIGNIN_SUCCESS",
  SIGNIN_FAIL = "SIGNIN_FAIL",
  SIGNOUT_INPROGRESS = "SIGNOUT_INPROGRESS",
  SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS",
  SIGNOUT_FAIL = "SIGNOUT_FAIL",

  GET_USERDATA_INPROGRESS = "GET_USERDATA_INPROGRESS",
  GET_USERDATA_SUCCESS = "GET_USERDATA_SUCCESS",
  GET_USERDATA_FAIL = "GET_USERDATA_FAIL",
  GET_USERDATA_UNAUTHORISED = "GET_USERDATA_UNAUTHORISED",

  CREATE_CHARACTER_INPROGRESS = "CREATE_CHARACTER_INPROGRESS",
  CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS",
  CREATE_CHARACTER_FAIL = "CREATE_CHARACTER_FAIL",
  CREATE_CHARACTER_UNAUTHORISED = "CREATE_CHARACTER_UNAUTHORISED",
  UPDATE_CHARACTER_INPROGRESS = "UPDATE_CHARACTER_INPROGRESS",
  UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS",
  UPDATE_CHARACTER_FAIL = "UPDATE_CHARACTER_FAIL",
  UPDATE_CHARACTER_UNAUTHORISED = "UPDATE_CHARACTER_UNAUTHORISED",
  DELETE_CHARACTER_INPROGRESS = "DELETE_CHARACTER_INPROGRESS",
  DELETE_CHARACTER_SUCCESS = "DELETE_CHARACTER_SUCCESS",
  DELETE_CHARACTER_FAIL = "DELETE_CHARACTER_FAIL",
  DELETE_CHARACTER_UNAUTHORISED = "DELETE_CHARACTER_UNAUTHORISED",

  GET_SPELL_INPROGRESS = "GET_SPELL_INPROGRESS",
  GET_SPELL_SUCCESS = "GET_SPELL_SUCCESS",
  GET_SPELL_FAIL = "GET_SPELL_FAIL",
  GET_SPELL_UNAUTHORISED = "GET_SPELL_UNAUTHORISED",
  GET_LIGHTSPELLSWITHFILTERS_INPROGRESS = "GET_LIGHTSPELLSWITHFILTERS_INPROGRESS",
  GET_LIGHTSPELLSWITHFILTERS_SUCCESS = "GET_LIGHTSPELLSWITHFILTERS_SUCCESS",
  GET_LIGHTSPELLSWITHFILTERS_FAIL = "GET_LIGHTSPELLSWITHFILTERS_FAIL",
  GET_LIGHTSPELLSWITHFILTERS_UNAUTHORISED = "GET_LIGHTSPELLSWITHFILTERS_UNAUTHORISED",

  SET_FILTERS_INPROGRESS = "SET_FILTERS_INPROGRESS",
  SET_FILTERS_SUCCESS = "SET_FILTERS_SUCCESS",
  SET_FILTERS_FAIL = "SET_FILTERS_FAIL",
  SET_FILTERS_UNAUTHORISED = "SET_FILTERS_UNAUTHORISED"

}

export default ActionTypeKeys;
