export enum ActionTypeStates {
  INPROGRESS = "_INPROGRESS",
  SUCCESS = "_SUCCESS",
  FAIL = "_FAIL"
}

enum ActionTypeKeys {
  SIGNIN_INPROGRESS = "SIGNIN_INPROGRESS",
  SIGNIN_SUCCESS = "SIGNIN_SUCCESS",
  SIGNIN_FAIL = "SIGNIN_FAIL",
  SIGNOUT_INPROGRESS = "SIGNOUT_INPROGRESS",
  SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS",
  SIGNOUT_FAIL = "SIGNOUT_FAIL",

  GET_USERDATA_INPROGRESS = "GET_USERDATA_INPROGRESS",
  GET_USERDATA_SUCCESS = "GET_USERDATA_SUCCESS",
  GET_USERDATA_FAIL = "GET_USERDATA_FAIL",
  GET_USERDATA_UNAUTHORISED_FAIL = "GET_USERDATA_UNAUTHORISED_FAIL",

  CREATE_CHARACTER_INPROGRESS = "CREATE_CHARACTER_INPROGRESS",
  CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS",
  CREATE_CHARACTER_FAIL = "CREATE_CHARACTER_FAIL",
  CREATE_CHARACTER_UNAUTHORISED_FAIL = "CREATE_CHARACTER_UNAUTHORISED_FAIL",
  UPDATE_CHARACTER_INPROGRESS = "UPDATE_CHARACTER_INPROGRESS",
  UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS",
  UPDATE_CHARACTER_FAIL = "UPDATE_CHARACTER_FAIL",
  UPDATE_CHARACTER_UNAUTHORISED_FAIL = "UPDATE_CHARACTER_UNAUTHORISED_FAIL",

  GET_SPELL_INPROGRESS = "GET_SPELL_INPROGRESS",
  GET_SPELL_SUCCESS = "GET_SPELL_SUCCESS",
  GET_SPELL_FAIL = "GET_SPELL_FAIL",
  GET_SPELL_UNAUTHORISED_FAIL = "GET_SPELL_UNAUTHORISED_FAIL",
  GET_LIGHTSPELLSWITHFILTERS_INPROGRESS = "GET_LIGHTSPELLSWITHFILTERS_INPROGRESS",
  GET_LIGHTSPELLSWITHFILTERS_SUCCESS = "GET_LIGHTSPELLSWITHFILTERS_SUCCESS",
  GET_LIGHTSPELLSWITHFILTERS_FAIL = "GET_LIGHTSPELLSWITHFILTERS_FAIL",
  GET_LIGHTSPELLSWITHFILTERS_UNAUTHORISED_FAIL = "GET_LIGHTSPELLSWITHFILTERS_UNAUTHORISED_FAIL"
}

export default ActionTypeKeys;
